import os
from pathlib import Path

script_path = Path(__file__).resolve()
output_dir = script_path.parent.parent / 'output'
doc_dir = script_path.parent.parent

def read_out(name):
    p = output_dir / f"{name}.txt"
    try: return p.read_text(encoding='utf-8')
    except: return ""

INDEX_MD = f"""# INDEX.md
| File | Generated By | Hand-written Parts |
|---|---|---|
| 00-project-fact-sheet.md | scripts/builder.py, scripts/master_audit.py | ANALYST NOTES (INFERRED) |
| 00-summary.md | scripts/builder.py, scripts/master_audit.py | ANALYST NOTES (INFERRED) |
| 02-templates.md | scripts/builder.py, scripts/master_audit2.py | None |
| 04-non-fetch-requests.md | scripts/builder.py, scripts/master_audit.py | None |
| 06-non-browser-clients.md | scripts/builder.py, scripts/master_audit.py | None |
| 07-source-verified-facts.md | scripts/builder.py | None |
| 08-xss-surface.md | scripts/builder.py, scripts/master_audit2.py | None |
| 09-api-gap-analysis.md | scripts/builder.py | ANALYST NOTES (INFERRED) |
| 10-role-matrix.md | scripts/builder.py, scripts/master_audit2.py | None |
| 11-test-db-plan.md | scripts/builder.py | None |
"""

FACT_SHEET_MD = f"""# 00-project-fact-sheet.md

## 3a. Dashboard Check
```
{read_out('dashboard_check')}
```
ANALYST NOTES (INFERRED):
- `dashboard.html` extends `base.html`.
- `base.html` has no timers.
- Therefore, `/dashboard` is NOT a wall screen. It is a static page.

## 3b. Admin Textual Expansion
```
{read_out('admin_expansion_5425')}
```
Schedules Fetches:
```
{read_out('schedules_fetches')}
```
ANALYST NOTES (INFERRED):
- The `schedules?date=` is called by `fetchSchedules(date)` in `scripts.html`. It repeats because it's bound to `workSchedRefreshTimer = setInterval(..., 30000)` and might be called via UI events (like `DOMContentLoaded` or line selection) leading to 5 calls initially before settling to the 30s timer.

## 3e. Observers
```
{read_out('observers')}
```

## 3f. trigger-pdf
```
{read_out('trigger_pdf_logic')}
```
"""

SUMMARY_MD = f"""# 00-summary.md

## WRITES TABLE
```
{read_out('writes')}
```

## LOCKOUT
```
{read_out('lockout_code')}
```
ANALYST NOTES (INFERRED):
- Code guarantees IP-based dictionary state tracking in memory.
- Does NOT persist across restarts.
- Locks out all accounts on a shared PC if IP fails 5 times.
"""

A6_MD = f"""# 06-non-browser-clients.md
```
{read_out('http_clients')}
```
"""

A2_MD = f"""# 02-templates.md
```
{read_out('a2_templates')}
```
"""

A4_MD = f"""# 04-non-fetch-requests.md
```
{read_out('a4_calls')}
```
"""

A8_MD = f"""# 08-xss-surface.md
```
{read_out('a8_xss')}
```
"""

A10_MD = f"""# 10-role-matrix.md
```
{read_out('a10_roles')}
```
"""

A9_MD = f"""# 09-api-gap-analysis.md
## POST FORMS
```
{read_out('admin_post_forms')}
```
ANALYST NOTES (INFERRED):
- The `Scoreboard` is a wall screen.
- Pilot should be `/admin` despite complexity.
- No `/api/me` endpoint exists.
"""

(doc_dir / "INDEX.md").write_text(INDEX_MD, encoding='utf-8')
(doc_dir / "00-project-fact-sheet.md").write_text(FACT_SHEET_MD, encoding='utf-8')
(doc_dir / "00-summary.md").write_text(SUMMARY_MD, encoding='utf-8')
(doc_dir / "06-non-browser-clients.md").write_text(A6_MD, encoding='utf-8')
(doc_dir / "02-templates.md").write_text(A2_MD, encoding='utf-8')
(doc_dir / "04-non-fetch-requests.md").write_text(A4_MD, encoding='utf-8')
(doc_dir / "08-xss-surface.md").write_text(A8_MD, encoding='utf-8')
(doc_dir / "10-role-matrix.md").write_text(A10_MD, encoding='utf-8')
(doc_dir / "09-api-gap-analysis.md").write_text(A9_MD, encoding='utf-8')

print("Builder script successfully generated Markdown files.")
