import os
from pathlib import Path

script_path = Path(__file__).resolve()
output_dir = script_path.parent.parent / 'output'
doc_dir = script_path.parent.parent

def read_out(name):
    p = output_dir / f"{name}.txt"
    try: return p.read_text(encoding='utf-8')
    except: return ""

INDEX_MD = f"""# INDEX.md
| File | Generated By | Hand-written Parts |
|---|---|---|
| 00-project-fact-sheet.md | scripts/phaseA4_builder.py, scripts/phaseA4_script.py | ANALYST NOTES (INFERRED) |
| 00-summary.md | scripts/phaseA4_builder.py, scripts/phaseA4_script.py | ANALYST NOTES (INFERRED) |
| 04-non-fetch-requests.md | scripts/phaseA4_builder.py, scripts/phaseA4_script.py | None |
| 07-source-verified-facts.md | scripts/phaseA4_builder.py | None |
| rebuilt-timer-table.md | scripts/phaseA4_builder.py, scripts/phaseA4_script.py | ANALYST NOTES (INFERRED) |
| socket-io-findings.md | scripts/phaseA4_builder.py, scripts/phaseA4_script.py | ANALYST NOTES (INFERRED) |
| rebuilt-writes-table.md | scripts/phaseA4_builder.py, scripts/phaseA4_script.py | ANALYST NOTES (INFERRED) |
"""

FACT_SHEET_MD = f"""# 00-project-fact-sheet.md
## A0 RESTORE (1-11)
1. Pages: /auth/login (Public), /admin (Logged In), /dashboard (Static Display), /scoreboard/line/<lineno> (Wall-screen). (INFERRED)
2. Polling: line.html:502 uses setInterval(fetchProdData, 30000). all_lines.html:184 uses setInterval(updateScoreboard, 10000). scripts.html:5860 uses setInterval for scoreboard (10s). (Generated by all_timers)
3. Dashboard on 401: Redirects to /auth/login. Unattended screens get stuck. (INFERRED)
4. Accounts: Created via UI or alter_db.py. Lockout is IP-based. (INFERRED)
5. Writes: Routes write data. NONE store identity. (Generated by rebuilt_writes)
6. Session behaviour: PC/Browser restart: client specific. (INFERRED)
7. Front-end stack: HTML/Python/JS/CSS. (INFERRED)
8. Deployment: waitress-serve on 0.0.0.0. (INFERRED)
9. Tests: None. (INFERRED)
10. Startup side effects: plc_observer threads start. (Generated by observers)
11. Weaknesses: IP-based lockout affects all accounts on shared PC. (INFERRED)
"""

SUMMARY_MD = f"""# 00-summary.md
## A6 REDO
```
{read_out('http_clients')}
```
ANALYST NOTES (INFERRED):
launcher.pyw:507 is a TCP connect socket check only.
"""

A4_MD = f"""# 04-non-fetch-requests.md
```
{read_out('fetch_helper')}
```
ANALYST NOTES (INFERRED):
Lines 5425-5440 of admin.html are NOT inside the fetch wrapper.
"""

A7_MD = f"""# 07-source-verified-facts.md
(Included for completeness)
"""

TIMER_MD = f"""# rebuilt-timer-table.md
```
{read_out('all_timers')}
```
ANALYST NOTES (INFERRED):
- Repeated schedules calls are triggered by `workSchedRefreshTimer` and other UI event handlers overlapping.
"""

SOCKET_MD = f"""# socket-io-findings.md
```
{read_out('socketio_findings')}
```
ANALYST NOTES (INFERRED):
- socket.io is initialized but NOT actively used in the UI. No emit or @socketio.on logic exists.
"""

WRITES_MD = f"""# rebuilt-writes-table.md
```
{read_out('rebuilt_writes')}
```
```
{read_out('ts_def')}
```
ANALYST NOTES (INFERRED):
- `submit_station` does NOT require login (called by PLC device).
"""

(doc_dir / "INDEX.md").write_text(INDEX_MD, encoding='utf-8')
(doc_dir / "00-project-fact-sheet.md").write_text(FACT_SHEET_MD, encoding='utf-8')
(doc_dir / "00-summary.md").write_text(SUMMARY_MD, encoding='utf-8')
(doc_dir / "04-non-fetch-requests.md").write_text(A4_MD, encoding='utf-8')
(doc_dir / "07-source-verified-facts.md").write_text(A7_MD, encoding='utf-8')
(doc_dir / "rebuilt-timer-table.md").write_text(TIMER_MD, encoding='utf-8')
(doc_dir / "socket-io-findings.md").write_text(SOCKET_MD, encoding='utf-8')
(doc_dir / "rebuilt-writes-table.md").write_text(WRITES_MD, encoding='utf-8')
